[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dluxshera"
version = "0.1.0"
description = "Shera / dLux-based astrometric modeling tools"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Dylan McKeithen" }
]

dependencies = [
  "dLux @ git+https://github.com/wakinget/dLux.git@d0ab6df843503535c05225b15197233144be3cf1",
  "dLuxToliman==0.3.0",
  "jax==0.4.30",
  "jaxlib==0.4.30",
  "numpy>=1.24",
  "scipy>=1.9",
  "astropy>=5.0",
  "matplotlib>=3.9",
  "tqdm>=4.67",
  "pandas>=1.5",
  "numpyro==0.18.0",
  "optax>=0.2.4",
  "equinox>=0.11.10",
  "chex>=0.1.88",
  "jaxtyping>=0.2.36",
  "zodiax>=0.4.1,<0.5",
  "interpax==0.3.12",
]

[project.optional-dependencies]
ml = [
  "torch>=2.2,<3",
  "PyYAML>=6.0",
]
notebooks = [
  "ipykernel>=6.31",
  "jupyterlab>=4.4",
  "ipywidgets",
  "jupyterlab_widgets",
]
dev = [
  "pytest>=7.4",
]
gui = [
  "PyQt6",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
markers = [
  "slow: marks tests as slow; deselect with '-m \"not slow\"'",
]
