from __future__ import annotations

from typing import Any, Mapping

import numpy as np

try:
    import torch
    from torch.utils.data import Dataset
except ModuleNotFoundError as exc:  # pragma: no cover - exercised in no-torch envs
    raise ModuleNotFoundError(
        "dluxshera.ml.torch_data requires PyTorch. Install the optional ML "
        "environment, for example `python -m pip install -e .[ml]`."
    ) from exc

from .catalog import SampleCatalog
from .noise import NoiseConfig, apply_pair_noise
from .pairs import PairManifest, PairRecord, PairSampler, make_reverse_pair_record
from .scaling import IntensityScaler

__all__ = ["DynamicPairDataset", "PairManifestDataset"]


def _record_to_tensors(
    *,
    catalog: SampleCatalog,
    reader: Any,
    record: PairRecord,
    scaler: IntensityScaler,
    noise_config: NoiseConfig,
    dynamic_seed_offset: int,
    second_noise_view: bool = False,
) -> dict[str, Any]:
    clean_a = reader.get(int(record.sample_a_index))
    clean_b = reader.get(int(record.sample_b_index))
    # Noise is applied after ordering, so observation-only noise remains tied
    # to the B role even when a reverse PairRecord swaps physical samples.
    image_a, image_b = apply_pair_noise(
        clean_a,
        clean_b,
        noise_config,
        pair_record_id=record.pair_record_id,
        dynamic_seed_offset=dynamic_seed_offset,
    )
    image_a = scaler.transform(image_a)
    image_b = scaler.transform(image_b)
    item = {
        "image_a": torch.from_numpy(np.asarray(image_a, dtype=np.float32)).unsqueeze(0),
        "image_b": torch.from_numpy(np.asarray(image_b, dtype=np.float32)).unsqueeze(0),
        "target_delta_z": torch.from_numpy(
            np.asarray(record.target_delta_z, dtype=np.float32)
        ),
        "target_delta_theta": torch.from_numpy(
            np.asarray(record.target_delta_theta, dtype=np.float32)
        ),
        "nuisance_delta": torch.from_numpy(np.asarray(record.nuisance_delta, dtype=np.float32)),
        "pair_record_id": record.pair_record_id,
        "sample_a_id": record.sample_a_id,
        "sample_b_id": record.sample_b_id,
        "eval_slice": record.eval_slice or "",
        "pair_family": record.pair_family,
        "dataset_family": record.dataset_family_a
        if record.dataset_family_a == record.dataset_family_b
        else f"{record.dataset_family_a}->{record.dataset_family_b}",
        "distance_bin_label": record.distance_bin_label or "",
        "fisher_distance_l2": torch.tensor(record.fisher_distance_l2, dtype=torch.float32),
        "changed_science_dimensions": torch.tensor(
            record.changed_science_dimensions,
            dtype=torch.int64,
        ),
    }
    if second_noise_view:
        image_a2, image_b2 = apply_pair_noise(
            clean_a,
            clean_b,
            noise_config,
            pair_record_id=record.pair_record_id,
            dynamic_seed_offset=dynamic_seed_offset + 1_000_000_007,
        )
        item["image_a_noise_view2"] = torch.from_numpy(
            np.asarray(scaler.transform(image_a2), dtype=np.float32)
        ).unsqueeze(0)
        item["image_b_noise_view2"] = torch.from_numpy(
            np.asarray(scaler.transform(image_b2), dtype=np.float32)
        ).unsqueeze(0)
    return item


class PairManifestDataset(Dataset):
    """Read fixed ordered pairs from a frozen pair manifest.

    This is an optional PyTorch adapter around the architecture-neutral catalog,
    shard reader, and pair-manifest records.  Use it when a training or
    evaluation loop should replay exactly the same ordered pairs every run.

    Parameters
    ----------
    catalog:
        Prepared sample catalog used to read images.
    pair_manifest:
        Frozen ordered-pair manifest.
    scaler:
        Optional image intensity scaler.  Defaults to raw image copies.
    noise_config:
        Optional noise/augmentation configuration.  A mapping is converted with
        ``NoiseConfig.from_dict``.
    second_noise_view:
        If ``True``, include ``image_a_noise_view2`` and
        ``image_b_noise_view2`` tensors generated by reapplying
        ``noise_config`` with a separate deterministic seed offset.
    shard_cache_size:
        Number of shard memory maps retained by the underlying image reader.

    Notes
    -----
    Items contain PyTorch tensors for ``image_a``, ``image_b``,
    ``target_delta_z``, ``target_delta_theta``, and ``nuisance_delta``, plus
    string metadata such as sample ids, pair family, and evaluation slice.  When
    ``second_noise_view=True``, items also contain ``image_a_noise_view2`` and
    ``image_b_noise_view2``.
    """

    def __init__(
        self,
        *,
        catalog: SampleCatalog,
        pair_manifest: PairManifest,
        scaler: IntensityScaler | None = None,
        noise_config: NoiseConfig | Mapping[str, Any] | None = None,
        second_noise_view: bool = False,
        shard_cache_size: int = 4,
    ) -> None:
        self.catalog = catalog
        self.records = tuple(pair_manifest.records)
        self.scaler = IntensityScaler() if scaler is None else scaler
        self.noise_config = (
            noise_config
            if isinstance(noise_config, NoiseConfig)
            else NoiseConfig.from_dict(noise_config)
        )
        self.second_noise_view = bool(second_noise_view)
        self.shard_cache_size = int(shard_cache_size)
        self._reader = None

    def __len__(self) -> int:
        return len(self.records)

    def _get_reader(self) -> Any:
        if self._reader is None:
            self._reader = self.catalog.image_reader(cache_size=self.shard_cache_size)
        return self._reader

    def __getitem__(self, index: int) -> dict[str, Any]:
        return _record_to_tensors(
            catalog=self.catalog,
            reader=self._get_reader(),
            record=self.records[int(index)],
            scaler=self.scaler,
            noise_config=self.noise_config,
            dynamic_seed_offset=int(index),
            second_noise_view=self.second_noise_view,
        )


class DynamicPairDataset(Dataset):
    """Generate deterministic dynamic training pairs for a seed and epoch.

    This optional PyTorch adapter asks :class:`PairSampler` for pairs on demand
    instead of replaying a frozen manifest.  It is useful when training should
    see a deterministic but broader stream of controlled comparisons than a
    fixed validation/test manifest.

    ``pairs_per_epoch`` is the total number of ordered examples.  When the
    sampler policy has ``include_reverse=True``, adjacent indices are generated
    from one sampled base pair: ``2k`` is ``(A, B)`` and ``2k+1`` is its
    semantic reverse ``(B, A)``.

    Parameters
    ----------
    catalog:
        Prepared sample catalog used to read images.
    sampler:
        Pair sampler containing the catalog, split registry, and pair policy.
    pairs_per_epoch:
        Number of ordered examples exposed by ``__len__``.
    seed:
        Base seed for deterministic pair sampling.
    science_split:
        Science-state split used for training pair selection.
    nuisance_split:
        Nuisance-state split used for training pair selection.
    scaler:
        Optional image intensity scaler.  Defaults to raw image copies.
    noise_config:
        Optional noise/augmentation configuration.  A mapping is converted with
        ``NoiseConfig.from_dict``.
    second_noise_view:
        If ``True``, include ``image_a_noise_view2`` and
        ``image_b_noise_view2`` tensors generated by reapplying
        ``noise_config`` with a separate deterministic seed offset.
    shard_cache_size:
        Number of shard memory maps retained by the underlying image reader.
    """

    def __init__(
        self,
        *,
        catalog: SampleCatalog,
        sampler: PairSampler,
        pairs_per_epoch: int,
        seed: int,
        science_split: str = "train",
        nuisance_split: str = "train",
        scaler: IntensityScaler | None = None,
        noise_config: NoiseConfig | Mapping[str, Any] | None = None,
        second_noise_view: bool = False,
        shard_cache_size: int = 4,
    ) -> None:
        if int(pairs_per_epoch) < 1:
            raise ValueError("pairs_per_epoch must be >= 1.")
        if sampler.policy.include_reverse and int(pairs_per_epoch) % 2 != 0:
            raise ValueError(
                "include_reverse=True requires pairs_per_epoch to be even because "
                "pairs_per_epoch counts ordered examples."
            )
        self.catalog = catalog
        self.sampler = sampler
        self.pairs_per_epoch = int(pairs_per_epoch)
        self.seed = int(seed)
        self.science_split = str(science_split)
        self.nuisance_split = str(nuisance_split)
        self.scaler = IntensityScaler() if scaler is None else scaler
        self.noise_config = (
            noise_config
            if isinstance(noise_config, NoiseConfig)
            else NoiseConfig.from_dict(noise_config)
        )
        self.second_noise_view = bool(second_noise_view)
        self.shard_cache_size = int(shard_cache_size)
        self.epoch = 0
        self._reader = None

    def __len__(self) -> int:
        return self.pairs_per_epoch

    def set_epoch(self, epoch: int) -> None:
        """Set the deterministic epoch offset used by pair sampling."""
        self.epoch = int(epoch)

    def _get_reader(self) -> Any:
        if self._reader is None:
            self._reader = self.catalog.image_reader(cache_size=self.shard_cache_size)
        return self._reader

    def __getitem__(self, index: int) -> dict[str, Any]:
        ordered_index = int(index)
        include_reverse = bool(self.sampler.policy.include_reverse)
        base_pair_index = ordered_index // 2 if include_reverse else ordered_index
        pair_seed = self.seed + self.epoch * 1_000_003 + base_pair_index
        rng = np.random.default_rng(pair_seed)
        record = self.sampler.sample_pair(
            rng,
            science_split=self.science_split,
            nuisance_split=self.nuisance_split,
            split="train",
            eval_slice=None,
            epoch=self.epoch,
        )
        if include_reverse and ordered_index % 2 == 1:
            record = make_reverse_pair_record(record)
        return _record_to_tensors(
            catalog=self.catalog,
            reader=self._get_reader(),
            record=record,
            scaler=self.scaler,
            noise_config=self.noise_config,
            dynamic_seed_offset=pair_seed if self.noise_config.training_dynamic else 0,
            second_noise_view=self.second_noise_view,
        )
